application: ocorrencias-em-sao-paulo
version: 1
runtime: php55
api_version: 1

handlers:
- url: /theme
  static_dir: theme

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /ocorrencia.php
  script: theme/ocorrencia.php

- url: /
  script: index.php
