<?php
echo '
	<div id="footer">
		<div class="wrapper">
			<ul id="nav-footer">
				<li>Fontes 
					<ul>
						<li class="first"><a target="_blank" href="http://www.ssp.sp.gov.br/home/"><strong><strong>Secretaria de Segurança Pública de São Paulo</strong></a></li>
					</ul>
				</li> 
				<li>Ferramentas 
					<ul> 
						<li class="first"><a href="http://php.net/">PHP</a></li>
						<li><a href="http://mysql.com/">MySQL</a></li>
						<li><a href="http://code.google.com/">Google Code</a></li>
						<li><a href="http://craigsworks.com/projects/qtip/">qTip</a></li>
					</ul>
				</li>
			</ul>
			<p id="copyright"><a href="http://creativecommons.org/licenses/by-nc/2.5/br/" rel="license">Creative Commons Attribution-Noncommercial 2.5 Brazil License</a>.</p>
		</div>
	</div>

		<script type="text/javascript">
			var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
			document.write(unescape("%3Cscript src=\'" + gaJsHost + "google-analytics.com/ga.js\' type=\'text/javascript\'%3E%3C/script%3E"));
			</script>
			<script type="text/javascript">
			try {
			var pageTracker = _gat._getTracker("UA-11552017-1");
			pageTracker._trackPageview();
			} catch(err) {}
		</script>

	</body>
</html>';
  ?>